name: Docker web CI

on:
  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./web --file ./web/Dockerfile --tag yc3231996/yingkou-assethub-web:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PWD }}

    - name: Push Docker image
      run: docker push yc3231996/yingkou-assethub-web:latest
